site:
  title: AI Accelerate Bootcamp
  url: https://arckrish.github.io/bootcamp-instructions
  start_page: modules::welcome.adoc

ui:
  bundle:
    url: ./content/docs-ui/ui-bundle.zip
  supplemental_files: ./content/supplemental-ui

content:
  edit_url: 'https://github.com/arckrish/bootcamp-instructions/edit/main/{path}'
  sources:
    - url: ./
      start_path: content

output:
  dir: ./content/www

runtime:
  cache_dir: ./content/.cache/antora


runtime:
  cache_dir: ./.cache/antora
