runtime:
  cache_dir: ./.cache/antora

site:
  title: AI Accelerate Botocamp
  repo: bootcamp-instructions
  url: https://github.com/arckrish/bootcamp-instructions
  start_page: bootcamp-instructions::welcome.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.5/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll

output:
  clean: true
  dir: ./gh-pages
